version: '3'
services:
  mysql:
    image: mysql/mysql-server:5.7
    platform: linux/amd64
    container_name: aurora-verification
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 53306:3306
    volumes:
      - ./database/mysql_data:/docker-entrypoint-initdb.d
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
